services:
  frontend:
    image: myfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8082:3000"  # Change from 8081 to 8082
  backend:
    image: mybackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
